openapi: 3.0.3
info:
  title: SittingSpotDataLayer
  description: Data Layer managing internal storage for sitting spots.
  version: 1.0.0
servers:
  - url: https://sitting-spot-dl/api/v1
paths:
  /:
    get:
      summary: Get list of sitting spots
      description: Get list of sitting spots
      operationId: getSittingSpots
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SittingSpot'
    post:
      summary: Add a new sitting spot
      description: Add a new sitting spot
      operationId: addSittingSpot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SittingSpot'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SittingSpot'
        '400':
          description: Invalid input
  /{Id}:
    get:
      summary: Find sitting spot by ID
      description: Returns a single sitting spot
      operationId: getSittingSpotById
      parameters:
        - name: Id
          in: path
          description: ID of the sitting spot
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SittingSpot'
        '400':
          description: Invalid ID supplied
        '404':
          description: Sitting spot not found
    put:
      summary: Updates a sitting spot
      description: ''
      operationId: updatePetWithForm
      requestBody: 
        description: Custom labels to be added to the sitting spot
        content: 
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '404':
          description: Sitting spot not found
components:
  schemas:
    SittingSpot:
      type: object
      properties:
        id:
          type: string
          format: uuid
        location:
          type: object
          properties:
            x:
              type: number
            y:
              type: number
        tags:
          type: array
          items:
            type: object
            properties:
              tag:
                type: string
              value:
                type: string
        labels:
          type: array
          items:
            type: string
